# Generated by Django 2.2.24 on 2024-02-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('roundName', models.CharField(max_length=255)),
                ('cityName', models.CharField(max_length=255)),
                ('establishDate', models.DateTimeField()),
                ('img_url', models.CharField(max_length=255)),
                ('company_url', models.CharField(max_length=255)),
                ('brief', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('xn_href', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GongShang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('fullName', models.CharField(max_length=255)),
                ('legalPersonName', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('establishTime', models.DateTimeField(auto_now_add=True)),
                ('xn_href', models.CharField(max_length=255)),
                ('businessScope', models.TextField()),
                ('regCapital', models.CharField(max_length=255)),
                ('regStatus', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HuaXiang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youshi', models.CharField(max_length=255)),
                ('fenlei', models.TextField()),
                ('xn_href', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('brief', models.CharField(max_length=255)),
                ('highlight', models.CharField(max_length=255)),
                ('xn_href', models.CharField(max_length=255)),
                ('search_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RongZi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xn_href', models.CharField(max_length=255)),
                ('xn_id', models.CharField(max_length=50)),
                ('roundName', models.CharField(max_length=255)),
                ('postMoney', models.CharField(max_length=255)),
                ('money', models.CharField(max_length=255)),
                ('ratio', models.CharField(max_length=255)),
                ('newsLink', models.CharField(max_length=255)),
                ('investorStr', models.CharField(max_length=255)),
                ('fundingDate', models.DateTimeField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
